title: Mauro's Homepage
page-top-title: mcejasmarcovecchio
top-section-bg-text: Data Science
home-subtitle: Mauro Cejas Marcovecchio
copyright-text: '&copy; Mauro Cejas Marcovecchio 2026. All Rights Reserved.'
